language: node_js
node_js:
  - '10'

services:
  - docker

env:
  global:
    - CODECOV_TOKEN=152561a7-85a0-4dd0-86e3-28000089787d

before_script:
  # Host MySQL takes port 3306 so shutdown it.
  - sudo service mysql stop

script:
  - mkdir shared
  - docker-compose -f docker-compose/auth.ci.yml -f docker-compose/mysql.yml run -v "$PWD/shared:/app/shared" auth && docker-compose -f docker-compose/todo.ci.yml -f docker-compose/mysql.yml run -v "$PWD/shared:/app/shared" todo

after_success:
- bash <(curl -s https://codecov.io/bash)
