language: node_js
node_js:
  - '8'
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS todo_test;'
env:
  global:
    - CODECOV_TOKEN=152561a7-85a0-4dd0-86e3-28000089787d
  matrix:
    - DB_HOST=localhost DB_USER=root DB_PASSWORD= DB_NAME=todo_test SECRET=53cr3t-k3y TOKEN_EXPIRES_IN=24h
install:
  - npm install -g codecov
script:
  - npm run report-coverage