version: '2'
services:
  todo:
    container_name: todo-service
    restart: always
    build: .
    ports:
      - '3000:3000'
    env_file: .env
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'todo'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./bin:/docker-entrypoint-initdb.d
      - /var/lib/mysql