version: '3'
services:
  auth:
    container_name: auth_test
    command: ["./wait-for-it.sh", "db:3306", "--", "yarn", "test"]
    build: 
      context: ../auth
      dockerfile: ./docker/Dockerfile
    ports:
      - '3000:3000'
    env_file: ../auth/docker/.env.local
    depends_on:
      - db
