version: '3'
services:
  auth:
    container_name: auth
    restart: always
    build: 
      context: ../auth
      dockerfile: ./docker/Dockerfile
    ports:
      - '3000:3000'
    env_file: ../auth/docker/.env.local
    depends_on:
      - db
