version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - ../auth/bin:/docker-entrypoint-initdb.d
      - ../todo/bin:/docker-entrypoint-initdb.d
      - /var/lib/mysql
