version: '3'
services:
  todo:
    container_name: todo_test
    command: ["./wait-for-it.sh", "db:3306", "--", "yarn", "test"]
    build: 
      context: ../todo
      dockerfile: ./docker/Dockerfile
    ports:
      - '3001:3001'
    env_file: ../todo/docker/.env.local
    depends_on:
      - db
