version: '3'
services:
  todo:
    container_name: todo
    command: >
      sh -c "./wait-for-it.sh db:3306 -- yarn run coverage &&
             yarn run coverage:report &&
             bash <(curl -s https://codecov.io/bash)"
    build: 
      context: ../todo
      dockerfile: ./docker/Dockerfile
    ports:
      - '3001:3001'
    env_file: ../todo/docker/.env.local
    environment:
      - CODECOV_TOKEN=152561a7-85a0-4dd0-86e3-28000089787d
    depends_on:
      - db
